import { PageContent, FAQItem } from '@/types'

export const initialPageContents: PageContent[] = [
  {
    id: 'about',
    page: 'about',
    title: 'Sobre Nosotros',
    content: 'Bienvenido a E-commerce Demo, tu tienda online de confianza. Nos dedicamos a ofrecerte los mejores productos con la más alta calidad y un servicio excepcional.\n\nNuestra misión es proporcionar una experiencia de compra única, con productos cuidadosamente seleccionados y un equipo comprometido con tu satisfacción.\n\nTrabajamos constantemente para mejorar nuestros servicios y ofrecerte las mejores ofertas del mercado. Tu confianza es nuestra prioridad.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'contact',
    page: 'contact',
    title: 'Contacto',
    content: '',
    metadata: {
      email: 'contacto@ecommerce-demo.com',
      phone: '+1 (555) 123-4567',
      address: '123 Calle Principal',
      city: 'Ciudad',
      state: 'Estado',
      zipCode: '12345',
    },
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'faq',
    page: 'faq',
    title: 'Preguntas Frecuentes',
    content: 'Encuentra respuestas a las preguntas más comunes sobre nuestros productos y servicios.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'terms',
    page: 'terms',
    title: 'Términos y Condiciones',
    content: '1. Aceptación de los Términos\n\nAl acceder y utilizar este sitio web, aceptas cumplir con estos términos y condiciones. Si no estás de acuerdo con alguna parte de estos términos, no debes utilizar nuestro servicio.\n\n2. Uso del Servicio\n\nEl uso de nuestro servicio está sujeto a las siguientes condiciones:\n- Debes ser mayor de edad o tener el consentimiento de un tutor legal\n- No puedes utilizar el servicio para fines ilegales\n- Eres responsable de mantener la confidencialidad de tu cuenta\n- Debes proporcionar información precisa y actualizada\n\n3. Productos y Precios\n\nNos reservamos el derecho de modificar los precios de nuestros productos en cualquier momento. Los precios mostrados están sujetos a cambios sin previo aviso. Nos esforzamos por mantener la información precisa, pero no garantizamos que todos los productos estén disponibles en todo momento.\n\n4. Política de Devoluciones\n\nAceptamos devoluciones dentro de los 30 días posteriores a la compra, siempre que los productos estén en su estado original y sin usar. Para más información sobre devoluciones, consulta nuestra política de devoluciones completa.\n\n5. Propiedad Intelectual\n\nTodo el contenido de este sitio web, incluyendo textos, gráficos, logos, imágenes y software, es propiedad de E-commerce Demo y está protegido por las leyes de propiedad intelectual.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'help',
    page: 'help',
    title: 'Centro de Ayuda',
    content: 'Bienvenido al Centro de Ayuda de E-commerce Demo. Aquí encontrarás toda la información que necesitas para utilizar nuestro servicio de la mejor manera.\n\n¿Necesitas ayuda con tu cuenta?\n\nPuedes gestionar tu cuenta desde el panel de usuario, donde podrás actualizar tu información personal, ver tu historial de pedidos y gestionar tus preferencias.\n\n¿Tienes problemas con un pedido?\n\nSi tienes alguna pregunta o problema con un pedido, puedes contactarnos a través de nuestro formulario de contacto o por email. Estamos disponibles para ayudarte de lunes a viernes de 9:00 AM a 6:00 PM.\n\n¿Cómo puedo realizar una devolución?\n\nPara realizar una devolución, simplemente contacta con nuestro servicio al cliente y te proporcionaremos las instrucciones necesarias. Aceptamos devoluciones dentro de los 30 días posteriores a la compra.\n\n¿Necesitas más ayuda?\n\nSi no encuentras la respuesta que buscas, no dudes en contactarnos. Estamos aquí para ayudarte en todo lo que necesites.',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'shipping',
    page: 'shipping',
    title: 'Envíos y Devoluciones',
    content: 'Información sobre Envíos\n\nTiempos de envío:\n- Envío estándar: 3-7 días hábiles\n- Envío express: 1-3 días hábiles\n- Envío internacional: 7-14 días hábiles\n\nLos tiempos de envío varían según tu ubicación. Una vez que tu pedido sea enviado, recibirás un email con el número de seguimiento.\n\nCostos de envío:\n- Envío estándar: $5.990\n- Envío express: $12.990\n- Envío gratuito en pedidos superiores a $50.000\n\nPolítica de Devoluciones\n\nAceptamos devoluciones dentro de los 30 días posteriores a la compra, siempre que los productos estén en su estado original, sin usar y con el empaque original.\n\nPara iniciar una devolución:\n1. Contacta con nuestro servicio al cliente\n2. Proporciona el número de pedido\n3. Indica el motivo de la devolución\n4. Recibirás una etiqueta de envío prepagada\n\nEl costo de envío de la devolución corre por cuenta del cliente, a menos que el producto tenga un defecto. Una vez recibida la devolución, procesaremos el reembolso dentro de 5-7 días hábiles.',
    updatedAt: new Date().toISOString(),
  },
]

export const initialFAQItems: FAQItem[] = [
  {
    id: '1',
    question: '¿Cómo puedo realizar un pedido?',
    answer: 'Puedes realizar un pedido navegando por nuestro catálogo de productos, agregando los items que desees al carrito y luego procediendo al checkout. El proceso es simple y seguro.',
    order: 1,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    question: '¿Qué métodos de pago aceptan?',
    answer: 'Aceptamos tarjetas de crédito y débito (Visa, Mastercard, American Express), PayPal, y transferencias bancarias. Todos los pagos son procesados de forma segura.',
    order: 2,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    question: '¿Cuánto tiempo tarda el envío?',
    answer: 'Los tiempos de envío varían según tu ubicación. Generalmente, los pedidos se procesan en 1-2 días hábiles y el envío tarda entre 3-7 días hábiles. Recibirás un email con el número de seguimiento una vez que tu pedido sea enviado.',
    order: 3,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    question: '¿Puedo cancelar o modificar mi pedido?',
    answer: 'Puedes cancelar o modificar tu pedido dentro de las primeras 24 horas después de realizarlo. Después de ese período, el pedido ya estará en proceso de preparación. Contacta con nuestro servicio al cliente para más información.',
    order: 4,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    question: '¿Cuál es su política de devoluciones?',
    answer: 'Aceptamos devoluciones dentro de los 30 días posteriores a la compra, siempre que los productos estén en su estado original, sin usar y con el empaque original. El costo de envío de la devolución corre por cuenta del cliente, a menos que el producto tenga un defecto.',
    order: 5,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    question: '¿Ofrecen garantía en sus productos?',
    answer: 'Sí, todos nuestros productos vienen con garantía del fabricante. La duración de la garantía varía según el producto. Puedes encontrar los detalles de la garantía en la página de cada producto.',
    order: 6,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    question: '¿Cómo puedo rastrear mi pedido?',
    answer: 'Una vez que tu pedido sea enviado, recibirás un email con el número de seguimiento y un enlace para rastrear tu paquete en tiempo real. También puedes acceder a tu cuenta y ver el estado de tus pedidos.',
    order: 7,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    question: '¿Hacen envíos internacionales?',
    answer: 'Actualmente realizamos envíos a la mayoría de los países. Los costos y tiempos de envío internacional varían según el destino. Puedes verificar la disponibilidad de envío a tu país durante el proceso de checkout.',
    order: 8,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    question: '¿Cómo puedo contactar con el servicio al cliente?',
    answer: 'Puedes contactarnos a través de nuestro formulario de contacto en la página de Contacto, por email a contacto@ecommerce-demo.com, o por teléfono al +1 (555) 123-4567. Nuestro horario de atención es de lunes a viernes de 9:00 AM a 6:00 PM.',
    order: 9,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '10',
    question: '¿Ofrecen descuentos o promociones?',
    answer: 'Sí, regularmente ofrecemos descuentos y promociones especiales. Te recomendamos suscribirte a nuestro newsletter para recibir notificaciones sobre ofertas exclusivas, descuentos y nuevos productos.',
    order: 10,
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

