import { Product, Order, User } from '@/types'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Laptop Pro 15"',
    description: 'Laptop de alto rendimiento con procesador Intel i7 y 16GB RAM',
    price: 1299.99,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500',
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500',
      'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=500',
    ],
    category: 'Electronics',
    stock: 15,
    rating: 4.5,
    reviewsCount: 128,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Smartphone Ultra',
    description: 'Teléfono inteligente con pantalla AMOLED y cámara de 108MP',
    price: 899.99,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500',
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500',
      'https://images.unsplash.com/photo-1523206489230-c012c64b2b48?w=500',
    ],
    category: 'Electronics',
    stock: 32,
    rating: 4.8,
    reviewsCount: 256,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Auriculares Inalámbricos',
    description: 'Auriculares con cancelación de ruido activa y batería de 30h',
    price: 249.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
    category: 'Audio',
    stock: 48,
    rating: 4.6,
    reviewsCount: 89,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Smartwatch Pro',
    description: 'Reloj inteligente con monitor de salud y GPS integrado',
    price: 399.99,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
    category: 'Wearables',
    stock: 22,
    rating: 4.7,
    reviewsCount: 145,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Tablet 10"',
    description: 'Tablet con pantalla Retina y lápiz óptico incluido',
    price: 599.99,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500',
    category: 'Electronics',
    stock: 18,
    rating: 4.4,
    reviewsCount: 67,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Cámara DSLR',
    description: 'Cámara profesional con sensor de 24MP y grabación 4K',
    price: 1499.99,
    image: 'https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=500',
    category: 'Cameras',
    stock: 12,
    rating: 4.9,
    reviewsCount: 203,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockOrders: Order[] = [
  {
    id: '1',
    userId: '1',
    items: [
      {
        product: mockProducts[0],
        quantity: 1,
      },
    ],
    total: 1299.99,
    status: 'delivered',
    shippingAddress: {
      street: 'Calle Principal 123',
      city: 'Madrid',
      state: 'Madrid',
      zipCode: '28001',
      country: 'España',
    },
    paymentMethod: 'credit_card',
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
]

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@example.com',
    role: 'admin',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'customer',
    createdAt: new Date().toISOString(),
  },
]

